# Generated by Django 4.1.3 on 2022-11-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
